default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: sergio
  pool: 5

development:
  <<: *default
  database: botiqueRoR_development

test:
  <<: *default
  database: botiqueRoR_test

production:
  <<: *default
  database: botiqueRoR_production
  username: botiqueRoR
  password: <%= ENV['BOTIQUEROR_DATABASE_PASSWORD'] %>
